version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: 'postgres'
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "misha"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5400:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge